---
title: ""
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)
```

```{r initialize}
library(tidyverse)

simulation_settings <- tribble(
  ~ `Treat-Cov`, ~ `Cov-Outcome`, ~ `PVE`, ~ `PVE*`, ~ `Weight`, 
    "Linear",      "Linear",        "",      "0.95",   "Unweighted", 
    "Linear",      "Linear",        "",      "0.99",   "Unweighted", 
    "Linear",      "Linear",        "0.95",  "0.95",   "Weighted",
    "Linear",      "Linear",        "0.95",  "0.99",   "Weighted",
    "Linear",      "Linear",        "0.99",  "0.95",   "Weighted",
    "Linear",      "Linear",        "0.99",  "0.99",   "Weighted",
    "Non-linear",  "Linear",        "",      "0.95",   "Unweighted", 
    "Non-linear",  "Linear",        "",      "0.99",   "Unweighted", 
    "Non-linear",  "Linear",        "0.95",  "0.95",   "Weighted",
    "Non-linear",  "Linear",        "0.95",  "0.99",   "Weighted",
    "Non-linear",  "Linear",        "0.99",  "0.95",   "Weighted",
    "Non-linear",  "Linear",        "0.99",  "0.99",   "Weighted",
    "Linear",      "Non-linear",    "",      "0.95",   "Unweighted", 
    "Linear",      "Non-linear",    "",      "0.99",   "Unweighted", 
    "Linear",      "Non-linear",    "0.95",  "0.95",   "Weighted",
    "Linear",      "Non-linear",    "0.95",  "0.99",   "Weighted",
    "Linear",      "Non-linear",    "0.99",  "0.95",   "Weighted",
    "Linear",      "Non-linear",    "0.99",  "0.99",   "Weighted",
    "Non-linear",  "Non-linear",    "",      "0.95",   "Unweighted", 
    "Non-linear",  "Non-linear",    "",      "0.99",   "Unweighted", 
    "Non-linear",  "Non-linear",    "0.95",  "0.95",   "Weighted",
    "Non-linear",  "Non-linear",    "0.95",  "0.99",   "Weighted",
    "Non-linear",  "Non-linear",    "0.99",  "0.95",   "Weighted",
    "Non-linear",  "Non-linear",    "0.99",  "0.99",   "Weighted",
)
```

```{r}
box::use(./R/data_generation)
box::use(estimate = ./R/estimate_causal_effect)

n_replications <- 200
sample_size <- 200

get_data_impl <- function(treatment_covariate_relation, 
                          covariate_outcome_relation) {
  map(
    seq_len(n_replications), 
    \(dummy) data_generation$simulate_data(
      sample_size, treatment_covariate_relation, covariate_outcome_relation)
  )
}
get_data <- memoise::memoise(get_data_impl)

set.seed(314)
list_settings <- simulation_settings |> split(seq_len(nrow(simulation_settings)))
list_data <- list_settings |> 
  map(\(settings) get_data(settings$`Treat-Cov`, settings$`Cov-Outcome`))

dummy_data <- list_data[[1]][[1]]
true_effects_mu <- drop(t(dummy_data$true_eigenfunction_phi_values) %*% 
                          data_generation$true_effect_coefficients)

n_time_points <- length(dummy_data$time_grid)

dx <- diff(dummy_data$time_grid)
my_integrate <- function(x) {
  sum(dx * (x[-1] + x[-length(x)]) / 2)
}

run_simulation <- function(data_list, settings) {
  estimated_effects <- matrix(nrow = n_replications, ncol = n_time_points)
  ise <- double(n_replications)
  for (j in seq_len(n_replications)) {
    data <- data_list[[j]]
    
    pve <- settings$PVE
    pve_star <- settings$`PVE*`
    use_weight <- settings$Weight == "Weighted"
    
    mu_hat <- estimate$estimate_causal_effect(
      data$outcome_Y, data$functional_treatment_X, data$time_grid,
      data$covariates_C, pve, pve_star, use_weight)
    
    estimated_effects[j, ] <- mu_hat
    
    squared_error <- (mu_hat - true_effects_mu)^2
    ise[j] <- my_integrate(squared_error)
  }
  
  isb <- my_integrate((colMeans(estimated_effects) - true_effects_mu)^2)
  tibble(MISE = median(ise), AISE = mean(ise), ISB = isb)
}
```

```{r, cache=TRUE}
library(future)
library(furrr)

n_workers <- min(availableCores(), nrow(simulation_settings))
plan(multisession, workers = n_workers)

result <- future_map2_dfr(list_data, list_settings, run_simulation)

df <- cbind(simulation_settings, result)
```

```{r}
knitr::kable(df |> filter(`PVE*` == "0.95"), digits = 4)
```

```{r}
knitr::kable(df |> filter(`PVE*` == "0.99"), digits = 4)
```
